[package]
name = "data_base_homework"
version = "0.1.0"
edition = "2021"


[workspace]
members = ["./backend"]

backend = { path = "./backend", version = "0.1.0" }

[dependencies]
dioxus = { version = "0.2.4", features = ["desktop", "router"] }
dioxus-desktop = "0.2.3"
